### ISSUE TITLE
Error In WifiLedShopLight update

### ISSUE THREAD

**Issue by wkelton** [samhstein/sp108e_ws2815#16]
I receive this error occasionally in the HA logs:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 468, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 658, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sp108e_ws2815/pyledshop/WifiLedShopLight.py", line 214, in update
    state = bytearray(response)
TypeError: cannot convert 'NoneType' object to bytearray
```

This is due to the retry logic in WifiLedShopLight::send_command. The code will return None if the first time it tries to send the command if it fails. Checking the result variable (only if there should be a result - SYNC or GET_ID) before returning it will get the behavior expected (because the code throws an exception above if the number of attempts exceeds max). Also, need to move the socket creation inside the try block because the exception block closes the socket. Here is the diff:

```
diff --git a/pyledshop/WifiLedShopLight.py b/pyledshop/WifiLedShopLight.py
index cc396fa..5171477 100644
--- a/pyledshop/WifiLedShopLight.py
+++ b/pyledshop/WifiLedShopLight.py
@@ -184,10 +184,10 @@ class WifiLedShopLight(LightEntity):
     padded_data = data + [0] * (min_data_len - len(data))
     raw_data = [CommandFlag.START, *padded_data, command, CommandFlag.END]
     attempts = 0
-    self._sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
-    self._sock.settimeout(self._timeout)
     while True:
         try:
+            self._sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
+            self._sock.settimeout(self._timeout)
             self._sock.connect((self._ip, self._port))
             self._sock.sendall(bytes(raw_data))
             if command == command.GET_ID or command == command.SYNC:
@@ -206,7 +206,8 @@ class WifiLedShopLight(LightEntity):
                 print('break', command)
                 raise
 
-        return result
+        if not (command == command.GET_ID or command == command.SYNC) or result:
+            return result
 
 
   def update(self):
```

**Comment by samhstein** [comment]
thanks, merged into config-flow...

still not sure why sometimes it takes a few clicks to get the lights to come on.
will try to figure it out....

thanks, sam

**Comment by wkelton** [comment]
Awesome. Yeah, perplexing that sometimes it does not come on the first click.
